### ISSUE TITLE
【10 META】各业务都需要注意的安全问题

### ISSUE THREAD

**Issue by nekomeowww** [Matataki-io/matataki-frontend#997]
该 Issue 来自：@whyyouare
该问题系 Matataki 架构的 __重要安全问题__，该问题可能导致用户数据外泄和资产影响，同时影响到 Matataki 相关的业务上。

具体描述只有拥有权限的用户可以查看：[Issue on Coding.net](https://andoromeda.coding.net/p/smart-signature-future/backlog/issues/3877)

**Comment by whyouare111** [comment]
https://whyouare111.github.io/hexo-icarus-showcase/2021/01/08/matataki-auth/ 在这里用上锁博文的形式写了些想法
